const mantras = [
  // Original Best Mantras (20)
  "Every small step counts towards your bigger dreams ✨",
  "Progress over perfection, always 🌱",
  "You have the power to change your day, one moment at a time 💫",
  "Trust the process, embrace the journey 🌟",
  "Your potential is limitless, start where you are 🚀",
  "Small actions create big transformations 🌸",
  "Today is full of possibilities waiting for you 🌅",
  "You are stronger than you think, braver than you feel 💪",
  "Focus on progress, not perfection 📈",
  "Every moment is a fresh start 🔄",
  "You have everything within you to succeed 🎯",
  "Believe in your ability to figure things out 🧠",
  "Take it one breath, one step, one moment at a time 🫧",
  "Your consistency creates your destiny 🌊",
  "Small wins lead to big victories 🏆",
  "Growth happens outside your comfort zone 🌳",
  "Every challenge is an opportunity in disguise 💎",
  "You are capable of amazing things 🎭",
  "Focus on what you can control, release what you cannot 🍃",
  "Celebrate how far you've come 🎉",

  // Famous Wisdom Quotes (40)
  "The journey of a thousand miles begins with one step. — Lao Tzu 🛤️",
  "What we think, we become. — Buddha 🧘",
  "The only way to do great work is to love what you do. — Steve Jobs 💼",
  "Life is what happens when you're busy making other plans. — John Lennon 🎵",
  "In the middle of difficulty lies opportunity. — Albert Einstein 💡",
  "Be yourself; everyone else is already taken. — Oscar Wilde 🎭",
  "The unexamined life is not worth living. — Socrates 🤔",
  "To live is the rarest thing in the world. Most people exist, that is all. — Oscar Wilde 🌍",
  "Life is either a daring adventure or nothing at all. — Helen Keller 🌟",
  "The purpose of life is not to be happy. It is to be useful, honorable, compassionate. — Ralph Waldo Emerson 🌺",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle 🏛️",
  "The only impossible journey is the one you never begin. — Tony Robbins 🚶",
  "Everything you can imagine is real. — Pablo Picasso 🎨",
  "Act as if what you do makes a difference. It does. — William James 🌊",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill 🦁",
  "Happiness is not something ready made. It comes from your own actions. — Dalai Lama 😊",
  "The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb 🌳",
  "Your time is limited, don't waste it living someone else's life. — Steve Jobs ⏳",
  "If you want to lift yourself up, lift up someone else. — Booker T. Washington 🤝",
  "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison 💡",
  "A person who never made a mistake never tried anything new. — Albert Einstein 🔬",
  "The mind is everything. What you think you become. — Buddha 🧠",
  "Strive not to be a success, but rather to be of value. — Albert Einstein 💎",
  "Two roads diverged in a wood, and I—I took the one less traveled by. — Robert Frost 🌲",
  "The only true wisdom is in knowing you know nothing. — Socrates 📚",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt 🛠️",
  "It is during our darkest moments that we must focus to see the light. — Aristotle 🕯️",
  "Don't watch the clock; do what it does. Keep going. — Sam Levenson ⏰",
  "Whether you think you can or you think you can't, you're right. — Henry Ford 🚗",
  "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt 🌈",
  "It is never too late to be what you might have been. — George Eliot 🌅",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. — Ralph Waldo Emerson 🎯",
  "Everything has beauty, but not everyone sees it. — Confucius 🌸",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world. — Anne Frank 🌍",
  "Life isn't about finding yourself. Life is about creating yourself. — George Bernard Shaw 🎨",
  "When you reach the end of your rope, tie a knot in it and hang on. — Franklin D. Roosevelt 🪢",
  "Don't judge each day by the harvest you reap but by the seeds that you plant. — Robert Louis Stevenson 🌱",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela 🦅",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson 💫",
  "You must be the change you wish to see in the world. — Mahatma Gandhi 🌏",

  // Action-Oriented Quotes (30)
  "Start where you are. Use what you have. Do what you can. — Arthur Ashe 🎾",
  "The secret of getting ahead is getting started. — Mark Twain 🚀",
  "Don't wait. The time will never be just right. — Napoleon Hill ⏰",
  "Action is the foundational key to all success. — Pablo Picasso 🔑",
  "You don't have to be great to start, but you have to start to be great. — Zig Ziglar 🌟",
  "The way to get started is to quit talking and begin doing. — Walt Disney 🎬",
  "Do it now. Sometimes 'later' becomes 'never'. — Unknown ⚡",
  "Motivation is what gets you started. Habit is what keeps you going. — Jim Ryun 🏃",
  "A year from now you may wish you had started today. — Karen Lamb 📅",
  "If not now, when? — Hillel the Elder ⏳",
  "The harder you work for something, the greater you'll feel when you achieve it. — Unknown 💪",
  "Dream it. Wish it. Do it. — Unknown 🌠",
  "Don't stop when you're tired. Stop when you're done. — Unknown 🏁",
  "Wake up with determination. Go to bed with satisfaction. — Unknown 🌅",
  "Little by little, one travels far. — J.R.R. Tolkien 🗺️",
  "Do something today that your future self will thank you for. — Sean Patrick Flanery 🎁",
  "Great things never come from comfort zones. — Unknown 🌋",
  "Success doesn't just find you. You have to go out and get it. — Unknown 🎯",
  "The distance between your dreams and reality is called action. — Unknown 🌉",
  "Don't wish for it, work for it. — Unknown 🔨",
  "Sometimes later becomes never. Do it now. — Unknown 🔥",
  "Push yourself, because no one else is going to do it for you. — Unknown 💥",
  "Make today so awesome that yesterday gets jealous. — Unknown 😎",
  "The only way to do great work is to start. — Unknown 🚪",
  "Stop doubting yourself, work hard, and make it happen. — Unknown 💼",
  "Today's accomplishments were yesterday's impossibilities. — Robert H. Schuller 🌈",
  "If you get tired, learn to rest, not quit. — Banksy 🛋️",
  "A little progress each day adds up to big results. — Satya Nani 📊",
  "It always seems impossible until it's done. — Nelson Mandela ✅",
  "Believe you can and you're halfway there. — Theodore Roosevelt 🎈",

  // Resilience & Courage Quotes (30)
  "Courage is not the absence of fear, but the triumph over it. — Nelson Mandela 🦁",
  "Fall seven times, stand up eight. — Japanese Proverb 🥋",
  "It's not whether you get knocked down, it's whether you get up. — Vince Lombardi 🏈",
  "Strength doesn't come from what you can do. It comes from overcoming what you thought you couldn't. — Rikki Rogers 💪",
  "You are braver than you believe, stronger than you seem, and smarter than you think. — A.A. Milne 🐻",
  "Rock bottom became the solid foundation on which I rebuilt my life. — J.K. Rowling 🏗️",
  "You may have to fight a battle more than once to win it. — Margaret Thatcher ⚔️",
  "Life is 10% what happens to us and 90% how we react to it. — Charles R. Swindoll 🎭",
  "Difficult roads often lead to beautiful destinations. — Unknown 🗻",
  "When everything seems to be going against you, remember that the airplane takes off against the wind. — Henry Ford ✈️",
  "The comeback is always stronger than the setback. — Unknown 💥",
  "Stars can't shine without darkness. — Unknown ⭐",
  "Smooth seas do not make skillful sailors. — African Proverb ⛵",
  "Sometimes you don't realize your own strength until you come face to face with your greatest weakness. — Susan Gale 🌪️",
  "Persistence guarantees that results are inevitable. — Paramahansa Yogananda 🔄",
  "Every adversity carries with it the seed of an equal or greater benefit. — Napoleon Hill 🌱",
  "You never know how strong you are until being strong is your only choice. — Bob Marley 🎸",
  "What doesn't kill you makes you stronger. — Friedrich Nietzsche 🛡️",
  "The struggle you're in today is developing the strength you need for tomorrow. — Unknown 🌄",
  "Hardships often prepare ordinary people for an extraordinary destiny. — C.S. Lewis 🎪",
  "Pain is temporary. Quitting lasts forever. — Lance Armstrong 🚴",
  "The phoenix must burn to emerge. — Janet Fitch 🔥",
  "You can't calm the storm, so stop trying. What you can do is calm yourself. The storm will pass. — Timber Hawkeye 🌊",
  "Sometimes the bad things that happen in our lives put us directly on the path to the best things. — Unknown 🛤️",
  "Turn your wounds into wisdom. — Oprah Winfrey 📖",
  "The gem cannot be polished without friction, nor man perfected without trials. — Chinese Proverb 💎",
  "A smooth sea never made a skilled sailor. — Franklin D. Roosevelt 🌊",
  "In the depth of winter, I finally learned that there was in me an invincible summer. — Albert Camus ☀️",
  "Tough times never last, but tough people do. — Robert H. Schuller 🏋️",
  "The oak fought the wind and was broken, the willow bent when it must and survived. — Robert Jordan 🌳",

  // Creativity & Flow Quotes (30)
  "Creativity is intelligence having fun. — Albert Einstein 🎨",
  "The desire to create is one of the deepest yearnings of the human soul. — Dieter F. Uchtdorf 🌟",
  "Every child is an artist. The problem is how to remain an artist once we grow up. — Pablo Picasso 👶",
  "Creativity takes courage. — Henri Matisse 🎭",
  "The worst enemy to creativity is self-doubt. — Sylvia Plath 🦋",
  "To live a creative life, we must lose our fear of being wrong. — Joseph Chilton Pearce 🎪",
  "You can't use up creativity. The more you use, the more you have. — Maya Angelou ♾️",
  "Imagination is everything. It is the preview of life's coming attractions. — Albert Einstein 🎬",
  "Logic will get you from A to B. Imagination will take you everywhere. — Albert Einstein 🚀",
  "The chief enemy of creativity is good sense. — Pablo Picasso 🤡",
  "Don't think. Thinking is the enemy of creativity. — Ray Bradbury 🧠",
  "Creativity is contagious, pass it on. — Albert Einstein 🔗",
  "The creative adult is the child who survived. — Ursula K. Le Guin 🌈",
  "There is no innovation and creativity without failure. Period. — Brené Brown 💡",
  "Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep. — Scott Adams 🖼️",
  "The creation of something new is not accomplished by the intellect alone. — Carl Jung 🌌",
  "Art enables us to find ourselves and lose ourselves at the same time. — Thomas Merton 🎨",
  "The true sign of intelligence is not knowledge but imagination. — Albert Einstein 🌠",
  "Originality is nothing but judicious imitation. — Voltaire 🎭",
  "An essential aspect of creativity is not being afraid to fail. — Edwin Land 🎲",
  "To be creative means to be in love with life. — Osho 💕",
  "Every act of creation is first an act of destruction. — Pablo Picasso ⚡",
  "The only unique contribution that we will ever make in this world will be born of our creativity. — Brené Brown 🎁",
  "Creativity is seeing what everyone else has seen, and thinking what no one else has thought. — Albert Einstein 👁️",
  "Great things are done by a series of small things brought together. — Vincent Van Gogh 🌻",
  "Have no fear of perfection, you'll never reach it. — Salvador Dalí 🎪",
  "The best way to predict the future is to invent it. — Alan Kay 🔮",
  "Inspiration exists, but it has to find you working. — Pablo Picasso 🔨",
  "Art is not what you see, but what you make others see. — Edgar Degas 👀",
  "The artist is nothing without the gift, but the gift is nothing without work. — Émile Zola 🎁"
];

export const DailyMantra = () => {
  // Get consistent daily mantra based on date
  const getDailyMantra = () => {
    const today = new Date();
    const dayOfYear = Math.floor((today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24));
    return mantras[dayOfYear % mantras.length];
  };

  return (
    <div className="bg-white/10 backdrop-blur-sm border-b border-white/20">
      <div className="container py-3">
        <div className="flex items-center justify-center text-center">
          <p className="text-sm font-medium text-white/90 drop-shadow-md leading-relaxed max-w-2xl">
            {getDailyMantra()}
          </p>
        </div>
      </div>
    </div>
  );
};