// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdmhquczjguxfxiceugd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkbWhxdWN6amd1eGZ4aWNldWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDg3MzUsImV4cCI6MjA2NDc4NDczNX0.DEpRaq-ovOWeEVrnOMjw-pp2oowdasxz2P7mMla6qDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Verify client initialization
console.log('Supabase client initialized:', {
  url: SUPABASE_URL,
  hasKey: !!SUPABASE_PUBLISHABLE_KEY,
  keyPrefix: SUPABASE_PUBLISHABLE_KEY?.substring(0, 20) + '...'
});